### PR TITLE
fix(prometheus)_: reduce metrics cardinality

### LINKED ISSUE #41: Stop putting unconstrained values into metric labels
Currently the `rpc_requests_total` appears to be full of unconstrained values in the form of `request_err`:
```
jakubgs@node-01.do-ams3.proxy.prod:~ % c 0:8082/metrics | grep rpc_requests_total | grep request_err | head -n5 
rpc_requests_total{auth_token_masked="***",chain_id="1",chain_name="ethereum",evm_error_code="-32000",http_status="200",method="eth_feeHistory",provider_name="Nodefleet1",provider_url="https://eth-mainnet.alphafleet.io/",request_err="JSON-RPC error: ReceiptGen.GetReceipts: bn=22390945, txnIdx=0, nonce too high: address 0xBd9B34cCbb8db0FDECb532B1EAF5D46f5b673fE8, tx: 182605 state: 182600 (code -32000)"} 13
rpc_requests_total{auth_token_masked="***",chain_id="1",chain_name="ethereum",evm_error_code="-32000",http_status="200",method="eth_feeHistory",provider_name="Nodefleet1",provider_url="https://eth-mainnet.alphafleet.io/",request_err="JSON-RPC error: ReceiptGen.GetReceipts: bn=22391046, txnIdx=0, nonce too high: address 0xD1Fa51f2dB23A9FA9d7bb8437b89FB2E70c60cB7, tx: 326894 state: 326833 (code -32000)"} 9
rpc_requests_total{auth_token_masked="***",chain_id="1",chain_name="ethereum",evm_error_code="-32000",http_status="200",method="eth_feeHistory",provider_name="Nodefleet1",provider_url="https://eth-mainnet.alphafleet.io/",request_err="JSON-RPC error: ReceiptGen.GetReceipts: bn=22391076, txnIdx=0, nonce too high: address 0x43B603D4cdaed3DfA30855c9e354E300094A0A2D, tx: 56917 state: 56915 (code -32000)"} 4
rpc_requests_total{auth_token_masked="***",chain_id="1",chain_name="ethereum",evm_error_code="0",http_status="0",method="eth_blockNumber",provider_name="Nodefleet1",provider_url="https://eth-mainnet.alphafleet.io/",request_err="request failed: Post \"https://eth-mainnet.alphafleet.io/\": read tcp 172.17.1.3:38214->104.21.57.105:443: read: connection reset by peer"} 1
rpc_requests_total{auth_token_masked="***",chain_id="1",chain_name="ethereum",evm_error_code="0",http_status="200",method="eth_blockNumber",provider_name="Nodefleet1",provider_url="https://eth-mainnet.alphafleet.io/",request_err="none"} 63908
curl: (23) Failure writing output to destination
jakubgs@node-01.do-ams3.proxy.prod:~ % c 0:8082/metrics | grep rpc_requests_total | grep request_err | wc -l   
5456
```
This cannot continue as every new label is equivalent to a new metrics in the context of Prometheus and its backend.

From Prometheus docs:

>__CAUTION:__ Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

https://prometheus.io/docs/practices/naming/#labels

If you want to include an error in metrics you need to divide errors into a constrained list of named values.

The same rule applies to any values that are not constrained, like IDs. __Never__ put values like that into metric labels.

### PR DESCRIPTION
**Pull request by friofry**
- Reduced `rpc_requests_total` cardinality by removing high-cardinality labels and combining status codes
- Simplified `provider_status` to use only `chain_id` and `provider_name`
- Updated Grafana dashboard to match new metric structure

```
count(provider_status) - 69
count(validation_cycle_duration_seconds_count) - 1

Unique values per label in rpc_requests_total:
----------------------------------------
chain_id - 22
provider_name - 7
error_type - 3
status_code - 6
```

Closes #41

### CODE REVIEW

**Review by markoburcul — APPROVED** [review]
We would need to adjust the grafana dashboard but seems fine by me

File: rpc-health-checker/metrics/error_categories.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+
+	// UnknownError indicates unclassified errors
+	UnknownError ErrorCategory = "unknown_error"
+)
+
+// Custom error types for better error handling
+var (
+	ErrNetworkTimeout = errors.New("network timeout")
+	ErrNetworkRefused = errors.New("connection refused")
+	ErrNetworkReset   = errors.New("connection reset")
```
Comment (jakubgs) [inline rpc-health-checker/metrics/error_categories.go:37]: Is it just me or are none of those used?

**Review by jakubgs — APPROVED** [review]
Thank you for the quick fix. Appreciate it.
